version: "2"
services:
  product-api:
    build:
      context: .
      dockerfile: Dockerfile.ProductApi
  order-api:
    build:
      context: .
      dockerfile: Dockerfile.OrderApi
    ports:
      - "5000:80"
  customer-api:
    build:
      context: .
      dockerfile: Dockerfile.CustomerApi
